# Generated by Django 4.0.4 on 2022-07-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_remove_comentarios_teste'),
        ('core', '0002_pontosturisticos_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='comentarios',
            field=models.ManyToManyField(blank=True, null=True, to='comentarios.comentarios'),
        ),
    ]
