# Generated by Django 4.0.4 on 2022-07-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('core', '0003_pontosturisticos_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='enderecos',
            field=models.ManyToManyField(blank=True, to='endereco.endereco'),
        ),
    ]
