# Generated by Django 4.0.4 on 2022-07-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('core', '0004_pontosturisticos_enderecos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontosturisticos',
            name='enderecos',
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='enderecos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco'),
            preserve_default=False,
        ),
    ]
