# Generated by Django 4.0.4 on 2022-07-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='teste',
            field=models.BooleanField(default=True),
        ),
    ]
