# Generated by Django 4.0.4 on 2022-07-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_comentarios_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='teste',
        ),
    ]
