# Generated by Django 4.0.4 on 2022-07-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('horario_funcionamento', models.TextField(blank=True, null=True)),
                ('idade_minima', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
